---
  - name: Elk Playbook
    hosts: elk
    become: True
    tasks:

    - name: install docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install docker
      pip:
        name: docker
        state: present

    - name: set vm.max_map_count to 262144
      sysctl: name={{ item.key }} value={{ item.value }}
      with_items:
        - { key: "vm.max_map_count", value: "262144" } 
        
    - name: download and launch a elk containter
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"

    - name: Enable Docker Service
      systemd:
        name: docker
        enabled: yes        
